from typing import List, Optional
from pydantic import BaseModel, Field

class SearchTask(BaseModel):
    """Represents a single search query generated by the Planner."""
    query: str = Field(
        description="The specific search query to execute on the web."
    )
    status: str = Field(
        default="pending", 
        description="Current status: 'pending', 'completed', or 'failed'."
    )
    raw_result: Optional[str] = Field(
        default=None, 
        description="The raw text/HTML returned from the search tool."
    )

class Claim(BaseModel):
    """Represents a single factual statement extracted from the search results."""
    statement: str = Field(
        description="The distinct factual claim extracted from the text."
    )
    source_url: str = Field(
        description="The URL of the website where this claim was found."
    )
    confidence_score: float = Field(
        ge=0.0, le=1.0, 
        description="Agent's confidence in this extraction (0.0 to 1.0)."
    )
    is_verified: bool = Field(
        default=False, 
        description="True only if corroborated by the Verification Agent."
    )

class AgentState(BaseModel):
    """The central shared memory object for the entire multi-agent graph."""
    original_query: str = Field(
        description="The user's initial research request."
    )
    tasks: List[SearchTask] = Field(
        default_factory=list, 
        description="List of targeted search queries to execute."
    )
    extracted_claims: List[Claim] = Field(
        default_factory=list, 
        description="All claims pulled from the raw search results."
    )
    conflicts: List[str] = Field(
        default_factory=list, 
        description="Any contradictory information found between different sources."
    )
    final_report: str = Field(
        default="", 
        description="The final compiled markdown report."
    )